
running 2 tests
test tests::p2_test ... FAILED
test tests::p1_test ... ok

failures:

---- tests::p2_test stdout ----
thread 'tests::p2_test' panicked at day17\src\main.rs:164:35:
called `Result::unwrap()` on an `Err` value: Day Not Implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::p2_test

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

